### ISSUE TITLE
The live server is not working

### ISSUE THREAD

**Issue by Kj-is-escape** [sangonz193/openfing-server#1]
Hola, no sé si este repositorio está actualizado, pero open fing está caído, el frontend funciona pero el backend no. Estaría bueno que lo solucionaran porque estamos en época de parciales.

**Comment by sangonz193** [comment]
@Kj-is-escape Gracias por el aviso. Yo en particular ya no formo parte del proyecto, por lo que el repo puede que no tenga lo último. De todas formas, el sitio volvió a estar funcional. Éxitos en los parciales!
